export const REQUESTS_PATH = 'requests'
export const RESPONSES_PATH = 'responses'
export const CALL_RUNNER_PATH = 'callRunner'
export const CALL_GOOGLE_API_PATH = 'callGoogleApi'
export const CONTAINER_BUILDS_STATUS_PATH = 'container_build_statues'
