FROM cypress/base:6

# Handle input of test url (defaults to stage)
ARG test_url=https://barista-stage.firebaseapp.com
ENV CYPRESS_baseUrl=$test_url
RUN echo $CYPRESS_baseUrl

# Environment Variables
# good colors for most applications
ENV TERM xterm
# avoid million NPM install messages
ENV npm_config_loglevel warn

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Bundle app source
# COPY . . # TODO: Uncomment when all of source needs to be copied
COPY ./cypress/ ./cypress/
COPY ./build/ ./build/

# TODO: Only install dependencies used in building config files
# Install Dependencies
RUN npm install babel-core babel-cli babel-preset-env lodash firebase-admin

# Install Cypress
RUN npm install cypress

# Verify Cypress Installed correctly
RUN $(npm bin)/cypress verify

# Build Test Config
RUN npm run build:testConfig

# Run Cypress tests (URL set by ENV above)
ENTRYPOINT cypress run
