FROM cypress/base:6

# Handle input of environment (defaults to stage)
ARG test_url_arg=https://fireadmin-stage.firebaseapp.com
ENV CYPRESS_baseUrl=$test_url_arg
RUN echo $CYPRESS_baseUrl

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Bundle app source
COPY . .

# Install Dependencies
RUN npm install

# Install Cypress
RUN npm install --save-dev cypress

# Verify Cypress Installed correctly
RUN $(npm bin)/cypress verify

# Build Test Config
RUN npm run build test:config

# Run Cypress tests (URL set by ENV above)
ENTRYPOINT cypress run
